use aws_sdk_bedrockruntime::operation::converse_stream::ConverseStreamError;
use aws_sdk_bedrockruntime::types::error::ConverseStreamOutputError;
use aws_sdk_bedrockruntime::types::{ContentBlockDelta, ConverseStreamOutput, StopReason};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
/// Supported terminal reasons from a Bedrock Runtime message.
pub enum StopKind {
    /// The model completed the turn normally.
    EndTurn,
    /// The configured maximum output-token count was reached.
    MaximumTokens,
    /// A provider stop sequence ended generation.
    StopSequence,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
/// Cumulative token usage reported by Bedrock Runtime.
pub struct TokenUsage {
    /// Input tokens consumed by the request.
    pub input: u64,
    /// Output tokens generated by the response.
    pub output: u64,
    /// Provider-reported total tokens.
    pub total: u64,
}

#[derive(Clone, Debug, Eq, PartialEq)]
/// Validated semantic update projected from one SDK event-stream message.
pub enum StreamUpdate {
    /// The provider started the response message.
    MessageStarted,
    /// An ordered assistant text delta.
    TextDelta(String),
    /// The sole supported text content block ended.
    ContentBlockStopped,
    /// The response message ended with a supported reason.
    MessageStopped(StopKind),
    /// Final cumulative token usage.
    Usage(TokenUsage),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
/// Safe reason an SDK event stream could not be projected.
pub enum DecodeFailure {
    /// A known event arrived outside the required order.
    EventOutOfOrder,
    /// A required SDK field was absent.
    MissingRequiredField,
    /// A known semantic event is outside the qualified text-only subset.
    UnsupportedSemanticEvent,
    /// The SDK exposed a forward-compatible variant unknown to the adapter.
    UnknownSdkVariant,
    /// Provider usage could not be represented as portable unsigned counts.
    UsageOutOfRange,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
/// Safe provider failure categories produced from Bedrock SDK errors.
pub enum ProviderFailureKind {
    /// AWS authentication or model permission was rejected.
    AuthenticationOrPermissionDenied,
    /// The provider rejected the request shape.
    InvalidRequest,
    /// The selected model was unavailable.
    ModelUnavailable,
    /// The selected model timed out remotely.
    ModelTimedOut,
    /// The provider throttled the request.
    RateLimited,
    /// The requested provider resource did not exist.
    ResourceNotFound,
    /// The provider reported temporary service unavailability.
    ProviderOverloaded,
    /// Bedrock failed after accepting the request.
    ProviderFailed,
    /// The provider or SDK produced an unmodelled protocol shape.
    ProtocolFailed,
    /// Transport failed before a provider result was available.
    TransportFailed,
}

#[derive(Default)]
/// Stateful decoder for the qualified Bedrock text event-stream sequence.
pub struct StreamDecoder {
    started: bool,
    content_stopped: bool,
    message_stopped: bool,
    usage_seen: bool,
}

impl StreamDecoder {
    /// Applies one SDK event and returns its validated semantic projection.
    pub fn push(&mut self, event: ConverseStreamOutput) -> Result<StreamUpdate, DecodeFailure> {
        if self.usage_seen {
            return Err(DecodeFailure::EventOutOfOrder);
        }
        if event.is_unknown() {
            return Err(DecodeFailure::UnknownSdkVariant);
        }
        match event {
            ConverseStreamOutput::MessageStart(_) if !self.started => {
                self.started = true;
                Ok(StreamUpdate::MessageStarted)
            }
            ConverseStreamOutput::ContentBlockDelta(event)
                if self.started && !self.content_stopped =>
            {
                let delta = event.delta().ok_or(DecodeFailure::MissingRequiredField)?;
                if delta.is_unknown() {
                    return Err(DecodeFailure::UnknownSdkVariant);
                }
                match delta {
                    ContentBlockDelta::Text(text) => Ok(StreamUpdate::TextDelta(text.clone())),
                    ContentBlockDelta::Citation(_)
                    | ContentBlockDelta::Image(_)
                    | ContentBlockDelta::ReasoningContent(_)
                    | ContentBlockDelta::ToolResult(_)
                    | ContentBlockDelta::ToolUse(_) => Err(DecodeFailure::UnsupportedSemanticEvent),
                    _ => Err(DecodeFailure::UnknownSdkVariant),
                }
            }
            ConverseStreamOutput::ContentBlockStop(_) if self.started && !self.content_stopped => {
                self.content_stopped = true;
                Ok(StreamUpdate::ContentBlockStopped)
            }
            ConverseStreamOutput::MessageStop(event)
                if self.content_stopped && !self.message_stopped =>
            {
                let reason = event.stop_reason();
                if !StopReason::values().contains(&reason.as_str()) {
                    return Err(DecodeFailure::UnknownSdkVariant);
                }
                let stop = match reason {
                    StopReason::EndTurn => StopKind::EndTurn,
                    StopReason::MaxTokens => StopKind::MaximumTokens,
                    StopReason::StopSequence => StopKind::StopSequence,
                    _ => return Err(DecodeFailure::UnsupportedSemanticEvent),
                };
                self.message_stopped = true;
                Ok(StreamUpdate::MessageStopped(stop))
            }
            ConverseStreamOutput::Metadata(event) if self.message_stopped => {
                let usage = event.usage().ok_or(DecodeFailure::MissingRequiredField)?;
                let input = u64::try_from(usage.input_tokens())
                    .map_err(|_| DecodeFailure::UsageOutOfRange)?;
                let output = u64::try_from(usage.output_tokens())
                    .map_err(|_| DecodeFailure::UsageOutOfRange)?;
                let total = u64::try_from(usage.total_tokens())
                    .map_err(|_| DecodeFailure::UsageOutOfRange)?;
                self.usage_seen = true;
                Ok(StreamUpdate::Usage(TokenUsage {
                    input,
                    output,
                    total,
                }))
            }
            ConverseStreamOutput::ContentBlockStart(_) => {
                Err(DecodeFailure::UnsupportedSemanticEvent)
            }
            ConverseStreamOutput::ContentBlockDelta(_)
            | ConverseStreamOutput::ContentBlockStop(_)
            | ConverseStreamOutput::MessageStart(_)
            | ConverseStreamOutput::MessageStop(_)
            | ConverseStreamOutput::Metadata(_) => Err(DecodeFailure::EventOutOfOrder),
            _ => Err(DecodeFailure::UnknownSdkVariant),
        }
    }

    #[must_use]
    /// Returns whether final usage has closed the qualified sequence.
    pub const fn is_complete(&self) -> bool {
        self.usage_seen
    }
}

#[must_use]
/// Classifies a failed `ConverseStream` operation without exposing provider prose.
pub fn classify_converse_failure(error: &ConverseStreamError) -> ProviderFailureKind {
    match error {
        ConverseStreamError::AccessDeniedException(_) => {
            ProviderFailureKind::AuthenticationOrPermissionDenied
        }
        ConverseStreamError::ValidationException(_) => ProviderFailureKind::InvalidRequest,
        ConverseStreamError::ModelNotReadyException(_)
        | ConverseStreamError::ModelErrorException(_) => ProviderFailureKind::ModelUnavailable,
        ConverseStreamError::ModelTimeoutException(_) => ProviderFailureKind::ModelTimedOut,
        ConverseStreamError::ThrottlingException(_) => ProviderFailureKind::RateLimited,
        ConverseStreamError::ResourceNotFoundException(_) => ProviderFailureKind::ResourceNotFound,
        ConverseStreamError::ServiceUnavailableException(_) => {
            ProviderFailureKind::ProviderOverloaded
        }
        ConverseStreamError::InternalServerException(_)
        | ConverseStreamError::ModelStreamErrorException(_) => ProviderFailureKind::ProviderFailed,
        _ => ProviderFailureKind::ProtocolFailed,
    }
}

#[must_use]
/// Classifies an error delivered inside the Runtime output stream.
pub fn classify_output_failure(error: &ConverseStreamOutputError) -> ProviderFailureKind {
    match error {
        ConverseStreamOutputError::ValidationException(_) => ProviderFailureKind::InvalidRequest,
        ConverseStreamOutputError::ThrottlingException(_) => ProviderFailureKind::RateLimited,
        ConverseStreamOutputError::ServiceUnavailableException(_) => {
            ProviderFailureKind::ProviderOverloaded
        }
        ConverseStreamOutputError::InternalServerException(_)
        | ConverseStreamOutputError::ModelStreamErrorException(_) => {
            ProviderFailureKind::ProviderFailed
        }
        _ => ProviderFailureKind::ProtocolFailed,
    }
}
