no_classification_overrides = {
    ("usage_evidence", "muse-code.headless"): "selected_surface_absence",
    (
        "usage_evidence",
        "kimi-code.acp + kimi-code.headless",
    ): "upstream_unsupported",
    ("usage_evidence", "kimi-code.local-server"): "upstream_unsupported",
    ("usage_evidence", "grok-build.acp"): "contract_or_corpus_required",
    ("usage_evidence", "cline.acp"): "selected_surface_absence",
    ("usage_evidence", "cline.headless"): "selected_surface_absence",
    ("usage_evidence", "mistral-vibe.headless"): "selected_surface_absence",
    ("usage_evidence", "qoder.headless"): "selected_surface_absence",
    ("usage_evidence", "copilot-cli.acp"): "selected_surface_absence",
    ("usage_evidence", "goose.acp"): "selected_surface_absence",
    ("usage_evidence", "kiro.acp"): "selected_surface_absence",
    ("usage_evidence", "deepagents.acp"): "selected_surface_absence",
    ("structured_run", "gemini.live"): "operation_shape_not_applicable",
    ("structured_run", "openai.realtime"): "operation_shape_not_applicable",
    ("structured_run", "cline.acp"): "selected_surface_absence",
    ("structured_run", "copilot-cli.acp"): "selected_surface_absence",
    ("structured_run", "goose.acp"): "selected_surface_absence",
    ("structured_run", "kiro.acp"): "selected_surface_absence",
    ("structured_run", "deepagents.acp"): "selected_surface_absence",
    ("provider_session_catalogue", "oh-my-pi.rpc"): "selected_surface_absence",
    ("provider_session_import", "oh-my-pi.rpc"): "selected_surface_absence",
    ("provider_session_import", "deepseek-harness.local-server"): "selected_surface_absence",
    ("structured_run", "pi.sdk-sidecar"): "selected_surface_absence",
    ("provider_session_catalogue", "pi.sdk-sidecar"): "selected_surface_absence",
    ("provider_session_import", "pi.sdk-sidecar"): "selected_surface_absence",
}
generation_control_classifications = {
    ("output_token_limit", "muse-code.headless"): "selected_surface_absence",
    ("structured_output", "muse-code.headless"): "selected_surface_absence",
    ("output_token_limit", "cline.acp"): "selected_surface_absence",
    ("reasoning_selection", "cline.acp"): "selected_surface_absence",
    ("structured_output", "cline.acp"): "selected_surface_absence",
    ("output_token_limit", "cline.headless"): "selected_surface_absence",
    ("output_token_limit", "mistral-vibe.headless"): "selected_surface_absence",
    ("output_token_limit", "qoder.headless"): "selected_surface_absence",
    ("reasoning_selection", "cline.headless"): "selected_surface_absence",
    ("reasoning_selection", "mistral-vibe.headless"): "selected_surface_absence",
    ("reasoning_selection", "qoder.headless"): "selected_surface_absence",
    ("structured_output", "cline.headless"): "selected_surface_absence",
    ("structured_output", "mistral-vibe.headless"): "selected_surface_absence",
    ("structured_output", "qoder.headless"): "selected_surface_absence",
    ("output_token_limit", "copilot-cli.acp"): "selected_surface_absence",
    ("reasoning_selection", "copilot-cli.acp"): "selected_surface_absence",
    ("structured_output", "copilot-cli.acp"): "selected_surface_absence",
    ("output_token_limit", "goose.acp"): "selected_surface_absence",
    ("output_token_limit", "kiro.acp"): "selected_surface_absence",
    ("output_token_limit", "deepagents.acp"): "selected_surface_absence",
    ("reasoning_selection", "goose.acp"): "selected_surface_absence",
    ("reasoning_selection", "kiro.acp"): "selected_surface_absence",
    ("reasoning_selection", "deepagents.acp"): "selected_surface_absence",
    ("structured_output", "goose.acp"): "selected_surface_absence",
    ("structured_output", "kiro.acp"): "selected_surface_absence",
    ("structured_output", "deepagents.acp"): "selected_surface_absence",
    ("output_token_limit", "command-code.headless"): "selected_surface_absence",
    ("reasoning_selection", "command-code.headless"): "selected_surface_absence",
    ("structured_output", "command-code.headless"): "selected_surface_absence",
    ("output_token_limit", "deepseek-harness.jsonrpc"): "selected_surface_absence",
    ("reasoning_selection", "deepseek-harness.jsonrpc"): "selected_surface_absence",
    ("structured_output", "deepseek-harness.jsonrpc"): "selected_surface_absence",
    ("output_token_limit", "zcode.app-server"): "selected_surface_absence",
    ("reasoning_selection", "zcode.app-server"): "selected_surface_absence",
    ("structured_output", "zcode.app-server"): "selected_surface_absence",
    ("output_token_limit", "deepseek-harness.local-server"): "selected_surface_absence",
    ("reasoning_selection", "deepseek-harness.local-server"): "selected_surface_absence",
    ("structured_output", "deepseek-harness.local-server"): "selected_surface_absence",
    ("output_token_limit", "oh-my-pi.rpc"): "selected_surface_absence",
    ("structured_output", "oh-my-pi.rpc"): "selected_surface_absence",
    ("output_token_limit", "antigravity.catalogue + antigravity.headless"): "upstream_unsupported",
    ("output_token_limit", "cursor-agent.catalogue + cursor-agent.acp + cursor-agent.headless"): "upstream_unsupported",
    ("structured_output", "cursor-agent.catalogue + cursor-agent.acp + cursor-agent.headless"): "upstream_unsupported",
    ("output_token_limit", "qwen.headless"): "contract_or_corpus_required",
    ("structured_output", "qwen.headless"): "contract_or_corpus_required",
    ("output_token_limit", "alibaba.conversations"): "upstream_unsupported",
    ("reasoning_selection", "alibaba.conversations"): "contract_or_corpus_required",
    ("structured_output", "alibaba.conversations"): "upstream_unsupported",
    ("reasoning_selection", "bedrock.catalogue; bedrock.runtime"): "contract_or_corpus_required",
    ("structured_output", "bedrock.catalogue; bedrock.runtime"): "contract_or_corpus_required",
    ("output_token_limit", "claude-agent.acp"): "upstream_unsupported",
    ("structured_output", "claude-agent.acp"): "upstream_unsupported",
    ("output_token_limit", "claude-code.headless; claude-code.response-only"): "upstream_unsupported",
    ("structured_output", "claude-code.headless; claude-code.response-only"): "upstream_unsupported",
    ("output_token_limit", "anthropic.managed-agent"): "operation_shape_not_applicable",
    ("reasoning_selection", "anthropic.managed-agent"): "operation_shape_not_applicable",
    ("structured_output", "anthropic.managed-agent"): "operation_shape_not_applicable",
    ("structured_output", "anthropic.messages"): "contract_or_corpus_required",
    ("output_token_limit", "pi.rpc"): "upstream_unsupported",
    ("reasoning_selection", "pi.rpc"): "contract_or_corpus_required",
    ("structured_output", "pi.rpc"): "upstream_unsupported",
    ("output_token_limit", "pi.sdk-sidecar"): "upstream_unsupported",
    ("structured_output", "pi.sdk-sidecar"): "upstream_unsupported",
    ("structured_output", "deepseek.continuation"): "upstream_unsupported",
    ("output_token_limit", "gemini-cli.acp + gemini-cli.headless"): "contract_or_corpus_required",
    ("reasoning_selection", "gemini-cli.acp + gemini-cli.headless"): "contract_or_corpus_required",
    ("structured_output", "gemini-cli.acp + gemini-cli.headless"): "upstream_unsupported",
    ("structured_output", "gemini.live"): "upstream_unsupported",
    ("reasoning_selection", "llama-cpp.attached"): "contract_or_corpus_required",
    ("structured_output", "llama-cpp.attached"): "contract_or_corpus_required",
    ("output_token_limit", "kimi-code.acp + kimi-code.headless"): "upstream_unsupported",
    ("structured_output", "kimi-code.acp + kimi-code.headless"): "upstream_unsupported",
    ("output_token_limit", "kimi-code.local-server"): "upstream_unsupported",
    ("structured_output", "kimi-code.local-server"): "upstream_unsupported",
    ("structured_output", "kimi-platform.chat"): "upstream_unsupported",
    ("output_token_limit", "codex.app-server; codex.exec"): "upstream_unsupported",
    ("structured_output", "openai.realtime"): "upstream_unsupported",
    ("output_token_limit", "opencode.http"): "upstream_unsupported",
    ("structured_output", "xai.responses-websocket"): "ready_operator_hold",
    ("output_token_limit", "grok-build.acp"): "upstream_unsupported",
    ("reasoning_selection", "grok-build.acp"): "contract_or_corpus_required",
    ("structured_output", "grok-build.acp"): "upstream_unsupported",
}
input_callback_classifications = {
    ("attachments", "muse-code.headless"): "selected_surface_absence",
    ("consumer_tool_exchange", "muse-code.headless"): "selected_surface_absence",
    ("permission_exchange", "muse-code.headless"): "selected_surface_absence",
    ("question_exchange", "muse-code.headless"): "selected_surface_absence",
    ("external_search", "muse-code.headless"): "selected_surface_absence",
    ("attachments", "cline.acp"): "selected_surface_absence",
    ("consumer_tool_exchange", "cline.acp"): "selected_surface_absence",
    ("permission_exchange", "cline.acp"): "selected_surface_absence",
    ("question_exchange", "cline.acp"): "selected_surface_absence",
    ("external_search", "cline.acp"): "selected_surface_absence",
    ("attachments", "cline.headless"): "selected_surface_absence",
    ("attachments", "mistral-vibe.headless"): "selected_surface_absence",
    ("attachments", "qoder.headless"): "selected_surface_absence",
    ("consumer_tool_exchange", "cline.headless"): "selected_surface_absence",
    ("consumer_tool_exchange", "mistral-vibe.headless"): "selected_surface_absence",
    ("consumer_tool_exchange", "qoder.headless"): "selected_surface_absence",
    ("permission_exchange", "cline.headless"): "selected_surface_absence",
    ("permission_exchange", "mistral-vibe.headless"): "selected_surface_absence",
    ("permission_exchange", "qoder.headless"): "selected_surface_absence",
    ("question_exchange", "cline.headless"): "selected_surface_absence",
    ("question_exchange", "mistral-vibe.headless"): "selected_surface_absence",
    ("question_exchange", "qoder.headless"): "selected_surface_absence",
    ("external_search", "cline.headless"): "selected_surface_absence",
    ("external_search", "mistral-vibe.headless"): "selected_surface_absence",
    ("external_search", "qoder.headless"): "selected_surface_absence",
    ("attachments", "copilot-cli.acp"): "selected_surface_absence",
    ("consumer_tool_exchange", "copilot-cli.acp"): "selected_surface_absence",
    ("permission_exchange", "copilot-cli.acp"): "selected_surface_absence",
    ("question_exchange", "copilot-cli.acp"): "selected_surface_absence",
    ("external_search", "copilot-cli.acp"): "selected_surface_absence",
    ("attachments", "goose.acp"): "selected_surface_absence",
    ("attachments", "kiro.acp"): "selected_surface_absence",
    ("attachments", "deepagents.acp"): "selected_surface_absence",
    ("consumer_tool_exchange", "goose.acp"): "selected_surface_absence",
    ("consumer_tool_exchange", "kiro.acp"): "selected_surface_absence",
    ("consumer_tool_exchange", "deepagents.acp"): "selected_surface_absence",
    ("permission_exchange", "goose.acp"): "selected_surface_absence",
    ("permission_exchange", "kiro.acp"): "selected_surface_absence",
    ("permission_exchange", "deepagents.acp"): "selected_surface_absence",
    ("question_exchange", "goose.acp"): "selected_surface_absence",
    ("question_exchange", "kiro.acp"): "selected_surface_absence",
    ("question_exchange", "deepagents.acp"): "selected_surface_absence",
    ("external_search", "goose.acp"): "selected_surface_absence",
    ("external_search", "kiro.acp"): "selected_surface_absence",
    ("external_search", "deepagents.acp"): "selected_surface_absence",
    ("attachments", "command-code.headless"): "selected_surface_absence",
    ("consumer_tool_exchange", "command-code.headless"): "selected_surface_absence",
    ("permission_exchange", "command-code.headless"): "selected_surface_absence",
    ("question_exchange", "command-code.headless"): "selected_surface_absence",
    ("external_search", "command-code.headless"): "selected_surface_absence",
    ("attachments", "deepseek-harness.jsonrpc"): "selected_surface_absence",
    ("consumer_tool_exchange", "deepseek-harness.jsonrpc"): "selected_surface_absence",
    ("permission_exchange", "deepseek-harness.jsonrpc"): "selected_surface_absence",
    ("question_exchange", "deepseek-harness.jsonrpc"): "selected_surface_absence",
    ("external_search", "deepseek-harness.jsonrpc"): "selected_surface_absence",
    ("attachments", "zcode.app-server"): "selected_surface_absence",
    ("consumer_tool_exchange", "zcode.app-server"): "selected_surface_absence",
    ("permission_exchange", "zcode.app-server"): "selected_surface_absence",
    ("question_exchange", "zcode.app-server"): "selected_surface_absence",
    ("external_search", "zcode.app-server"): "selected_surface_absence",
    ("attachments", "deepseek-harness.local-server"): "selected_surface_absence",
    ("consumer_tool_exchange", "deepseek-harness.local-server"): "selected_surface_absence",
    ("permission_exchange", "deepseek-harness.local-server"): "selected_surface_absence",
    ("question_exchange", "deepseek-harness.local-server"): "selected_surface_absence",
    ("external_search", "deepseek-harness.local-server"): "selected_surface_absence",
    ("consumer_tool_exchange", "oh-my-pi.rpc"): "selected_surface_absence",
    ("permission_exchange", "oh-my-pi.rpc"): "selected_surface_absence",
    ("external_search", "oh-my-pi.rpc"): "selected_surface_absence",
    ("attachments", "antigravity.catalogue + antigravity.headless"): "upstream_unsupported",
    ("consumer_tool_exchange", "antigravity.catalogue + antigravity.headless"): "upstream_unsupported",
    ("permission_exchange", "antigravity.catalogue + antigravity.headless"): "upstream_unsupported",
    ("question_exchange", "antigravity.catalogue + antigravity.headless"): "upstream_unsupported",
    ("external_search", "antigravity.catalogue + antigravity.headless"): "upstream_unsupported",
    ("attachments", "cursor-agent.catalogue + cursor-agent.acp + cursor-agent.headless"): "contract_or_corpus_required",
    ("consumer_tool_exchange", "cursor-agent.catalogue + cursor-agent.acp + cursor-agent.headless"): "upstream_unsupported",
    ("permission_exchange", "cursor-agent.catalogue + cursor-agent.acp + cursor-agent.headless"): "contract_or_corpus_required",
    ("external_search", "cursor-agent.catalogue + cursor-agent.acp + cursor-agent.headless"): "contract_or_corpus_required",
    ("question_exchange", "cursor-agent.catalogue + cursor-agent.acp + cursor-agent.headless"): "contract_or_corpus_required",
    ("attachments", "qwen.headless"): "upstream_unsupported",
    ("consumer_tool_exchange", "qwen.headless"): "upstream_unsupported",
    ("permission_exchange", "qwen.headless"): "upstream_unsupported",
    ("external_search", "qwen.headless"): "upstream_unsupported",
    ("attachments", "alibaba.conversations"): "contract_or_corpus_required",
    ("consumer_tool_exchange", "alibaba.conversations"): "contract_or_corpus_required",
    ("permission_exchange", "alibaba.conversations"): "upstream_unsupported",
    ("external_search", "alibaba.conversations"): "contract_or_corpus_required",
    ("attachments", "bedrock.catalogue; bedrock.runtime"): "contract_or_corpus_required",
    ("consumer_tool_exchange", "bedrock.catalogue; bedrock.runtime"): "contract_or_corpus_required",
    ("permission_exchange", "bedrock.catalogue; bedrock.runtime"): "upstream_unsupported",
    ("external_search", "bedrock.catalogue; bedrock.runtime"): "upstream_unsupported",
    ("attachments", "claude-agent.acp"): "contract_or_corpus_required",
    ("consumer_tool_exchange", "claude-agent.acp"): "contract_or_corpus_required",
    ("external_search", "claude-agent.acp"): "contract_or_corpus_required",
    ("attachments", "claude-code.headless; claude-code.response-only"): "contract_or_corpus_required",
    ("consumer_tool_exchange", "claude-code.headless; claude-code.response-only"): "contract_or_corpus_required",
    ("permission_exchange", "claude-code.headless; claude-code.response-only"): "contract_or_corpus_required",
    ("external_search", "claude-code.headless; claude-code.response-only"): "contract_or_corpus_required",
    ("attachments", "anthropic.managed-agent"): "contract_or_corpus_required",
    ("permission_exchange", "anthropic.managed-agent"): "contract_or_corpus_required",
    ("external_search", "anthropic.managed-agent"): "contract_or_corpus_required",
    ("permission_exchange", "anthropic.messages"): "upstream_unsupported",
    ("consumer_tool_exchange", "pi.rpc"): "upstream_unsupported",
    ("permission_exchange", "pi.rpc"): "operation_shape_not_applicable",
    ("external_search", "pi.rpc"): "upstream_unsupported",
    ("consumer_tool_exchange", "pi.sdk-sidecar"): "upstream_unsupported",
    ("permission_exchange", "pi.sdk-sidecar"): "operation_shape_not_applicable",
    ("question_exchange", "pi.sdk-sidecar"): "selected_surface_absence",
    ("external_search", "pi.sdk-sidecar"): "upstream_unsupported",
    ("attachments", "deepseek.continuation"): "upstream_unsupported",
    ("permission_exchange", "deepseek.continuation"): "upstream_unsupported",
    ("external_search", "deepseek.continuation"): "upstream_unsupported",
    ("attachments", "gemini-cli.acp + gemini-cli.headless"): "composite_partial_only",
    ("consumer_tool_exchange", "gemini-cli.acp + gemini-cli.headless"): "composite_partial_only",
    ("permission_exchange", "gemini-cli.acp + gemini-cli.headless"): "contract_or_corpus_required",
    ("external_search", "gemini-cli.acp + gemini-cli.headless"): "contract_or_corpus_required",
    ("attachments", "gemini.live"): "operation_shape_not_applicable",
    ("consumer_tool_exchange", "gemini.live"): "contract_or_corpus_required",
    ("permission_exchange", "gemini.live"): "upstream_unsupported",
    ("external_search", "gemini.live"): "contract_or_corpus_required",
    ("attachments", "llama-cpp.attached"): "contract_or_corpus_required",
    ("consumer_tool_exchange", "llama-cpp.attached"): "contract_or_corpus_required",
    ("permission_exchange", "llama-cpp.attached"): "upstream_unsupported",
    ("external_search", "llama-cpp.attached"): "upstream_unsupported",
    ("attachments", "kimi-code.acp + kimi-code.headless"): "composite_partial_only",
    ("consumer_tool_exchange", "kimi-code.acp + kimi-code.headless"): "composite_partial_only",
    ("permission_exchange", "kimi-code.acp + kimi-code.headless"): "composite_partial_only",
    ("external_search", "kimi-code.acp + kimi-code.headless"): "contract_or_corpus_required",
    ("attachments", "kimi-code.local-server"): "ready_existing_contract",
    ("consumer_tool_exchange", "kimi-code.local-server"): "upstream_unsupported",
    ("external_search", "kimi-code.local-server"): "contract_or_corpus_required",
    ("attachments", "kimi-platform.chat"): "contract_or_corpus_required",
    ("consumer_tool_exchange", "kimi-platform.chat"): "contract_or_corpus_required",
    ("permission_exchange", "kimi-platform.chat"): "upstream_unsupported",
    ("external_search", "kimi-platform.chat"): "contract_or_corpus_required",
    ("attachments", "ollama.attached"): "contract_or_corpus_required",
    ("consumer_tool_exchange", "ollama.attached"): "contract_or_corpus_required",
    ("permission_exchange", "ollama.attached"): "upstream_unsupported",
    ("external_search", "ollama.attached"): "upstream_unsupported",
    ("attachments", "openai.realtime"): "contract_or_corpus_required",
    ("consumer_tool_exchange", "openai.realtime"): "contract_or_corpus_required",
    ("permission_exchange", "openai.realtime"): "upstream_unsupported",
    ("external_search", "openai.realtime"): "upstream_unsupported",
    ("attachments", "openai.background"): "contract_or_corpus_required",
    ("consumer_tool_exchange", "openai.background"): "upstream_unsupported",
    ("permission_exchange", "openai.background"): "upstream_unsupported",
    ("external_search", "openai.background"): "contract_or_corpus_required",
    ("permission_exchange", "codex.app-server; codex.exec"): "contract_or_corpus_required",
    ("consumer_tool_exchange", "opencode.http"): "contract_or_corpus_required",
    ("external_search", "opencode.http"): "contract_or_corpus_required",
    ("attachments", "xai.responses-websocket"): "ready_operator_hold",
    ("consumer_tool_exchange", "xai.responses-websocket"): "ready_operator_hold",
    ("permission_exchange", "xai.responses-websocket"): "upstream_unsupported",
    ("external_search", "xai.responses-websocket"): "ready_operator_hold",
    ("attachments", "grok-build.acp"): "contract_or_corpus_required",
    ("consumer_tool_exchange", "grok-build.acp"): "upstream_unsupported",
    ("permission_exchange", "grok-build.acp"): "upstream_unsupported",
    ("external_search", "grok-build.acp"): "contract_or_corpus_required",
    ("question_exchange", "qwen.headless"): "upstream_unsupported",
    ("question_exchange", "alibaba.conversations"): "upstream_unsupported",
    ("question_exchange", "bedrock.catalogue; bedrock.runtime"): "upstream_unsupported",
    ("question_exchange", "claude-code.headless; claude-code.response-only"): "contract_or_corpus_required",
    ("question_exchange", "anthropic.managed-agent"): "contract_or_corpus_required",
    ("question_exchange", "anthropic.messages"): "upstream_unsupported",
    ("question_exchange", "deepseek.continuation"): "upstream_unsupported",
    ("question_exchange", "gemini-cli.acp + gemini-cli.headless"): "contract_or_corpus_required",
    ("question_exchange", "gemini.live"): "upstream_unsupported",
    ("question_exchange", "llama-cpp.attached"): "upstream_unsupported",
    ("question_exchange", "kimi-code.acp + kimi-code.headless"): "composite_partial_only",
    ("question_exchange", "kimi-platform.chat"): "upstream_unsupported",
    ("question_exchange", "ollama.attached"): "upstream_unsupported",
    ("question_exchange", "openai.realtime"): "upstream_unsupported",
    ("question_exchange", "openai.background"): "upstream_unsupported",
    ("question_exchange", "xai.responses-websocket"): "upstream_unsupported",
    ("question_exchange", "grok-build.acp"): "upstream_unsupported",
}
session_continuity_classifications = {
    ("load_session", "muse-code.headless"): "operation_shape_not_applicable",
    ("resume_session", "muse-code.headless"): "operation_shape_not_applicable",
    ("native_session_close", "muse-code.headless"): "operation_shape_not_applicable",
    ("load_session", "cline.headless"): "operation_shape_not_applicable",
    ("load_session", "mistral-vibe.headless"): "operation_shape_not_applicable",
    ("load_session", "qoder.headless"): "operation_shape_not_applicable",
    ("resume_session", "cline.headless"): "operation_shape_not_applicable",
    ("resume_session", "mistral-vibe.headless"): "operation_shape_not_applicable",
    ("resume_session", "qoder.headless"): "operation_shape_not_applicable",
    ("native_session_close", "cline.headless"): "operation_shape_not_applicable",
    ("native_session_close", "mistral-vibe.headless"): "operation_shape_not_applicable",
    ("native_session_close", "qoder.headless"): "operation_shape_not_applicable",
    ("load_session", "cline.acp"): "contract_or_corpus_required",
    ("resume_session", "cline.acp"): "contract_or_corpus_required",
    ("native_session_close", "cline.acp"): "upstream_unsupported",
    ("load_session", "copilot-cli.acp"): "contract_or_corpus_required",
    ("resume_session", "copilot-cli.acp"): "contract_or_corpus_required",
    ("native_session_close", "copilot-cli.acp"): "upstream_unsupported",
    ("load_session", "goose.acp"): "contract_or_corpus_required",
    ("load_session", "kiro.acp"): "contract_or_corpus_required",
    ("load_session", "deepagents.acp"): "contract_or_corpus_required",
    ("resume_session", "goose.acp"): "contract_or_corpus_required",
    ("resume_session", "kiro.acp"): "contract_or_corpus_required",
    ("resume_session", "deepagents.acp"): "contract_or_corpus_required",
    ("native_session_close", "goose.acp"): "upstream_unsupported",
    ("native_session_close", "kiro.acp"): "upstream_unsupported",
    ("native_session_close", "deepagents.acp"): "upstream_unsupported",
    ("load_session", "command-code.headless"): "operation_shape_not_applicable",
    ("resume_session", "command-code.headless"): "operation_shape_not_applicable",
    ("native_session_close", "command-code.headless"): "operation_shape_not_applicable",
    ("load_session", "oh-my-pi.rpc"): "operation_shape_not_applicable",
    ("resume_session", "oh-my-pi.rpc"): "operation_shape_not_applicable",
    ("native_session_close", "oh-my-pi.rpc"): "operation_shape_not_applicable",
    ("load_session", "antigravity.catalogue + antigravity.headless"): "operation_shape_not_applicable",
    ("resume_session", "antigravity.catalogue + antigravity.headless"): "operation_shape_not_applicable",
    ("native_session_close", "antigravity.catalogue + antigravity.headless"): "upstream_unsupported",
    ("load_session", "cursor-agent.catalogue + cursor-agent.acp + cursor-agent.headless"): "contract_or_corpus_required",
    ("resume_session", "cursor-agent.catalogue + cursor-agent.acp + cursor-agent.headless"): "contract_or_corpus_required",
    ("native_session_close", "cursor-agent.catalogue + cursor-agent.acp + cursor-agent.headless"): "upstream_unsupported",
    ("load_session", "qwen.headless"): "operation_shape_not_applicable",
    ("resume_session", "qwen.headless"): "operation_shape_not_applicable",
    ("native_session_close", "qwen.headless"): "operation_shape_not_applicable",
    ("resume_session", "alibaba.conversations"): "selected_surface_absence",
    ("native_session_close", "alibaba.conversations"): "upstream_unsupported",
    ("load_session", "bedrock.catalogue; bedrock.runtime"): "operation_shape_not_applicable",
    ("resume_session", "bedrock.catalogue; bedrock.runtime"): "operation_shape_not_applicable",
    ("native_session_close", "bedrock.catalogue; bedrock.runtime"): "operation_shape_not_applicable",
    ("load_session", "claude-code.headless; claude-code.response-only"): "operation_shape_not_applicable",
    ("resume_session", "claude-code.headless; claude-code.response-only"): "operation_shape_not_applicable",
    ("native_session_close", "claude-code.headless; claude-code.response-only"): "operation_shape_not_applicable",
    ("load_session", "anthropic.managed-agent"): "shared_contract_expansion_required",
    ("resume_session", "anthropic.managed-agent"): "shared_contract_expansion_required",
    ("native_session_close", "anthropic.managed-agent"): "upstream_unsupported",
    ("load_session", "anthropic.messages"): "operation_shape_not_applicable",
    ("resume_session", "anthropic.messages"): "operation_shape_not_applicable",
    ("native_session_close", "anthropic.messages"): "operation_shape_not_applicable",
    ("load_session", "pi.rpc"): "ready_existing_contract",
    ("resume_session", "pi.rpc"): "ready_existing_contract",
    ("native_session_close", "pi.rpc"): "upstream_unsupported",
    ("native_session_close", "pi.sdk-sidecar"): "selected_surface_absence",
    ("load_session", "deepseek.continuation"): "operation_shape_not_applicable",
    ("resume_session", "deepseek.continuation"): "operation_shape_not_applicable",
    ("native_session_close", "deepseek.continuation"): "operation_shape_not_applicable",
    ("load_session", "deepseek-harness.local-server"): "selected_surface_absence",
    ("resume_session", "deepseek-harness.local-server"): "selected_surface_absence",
    ("native_session_close", "deepseek-harness.local-server"): "selected_surface_absence",
    ("load_session", "gemini-cli.acp + gemini-cli.headless"): "upstream_ordering_blocked",
    ("resume_session", "gemini-cli.acp + gemini-cli.headless"): "upstream_unsupported",
    ("native_session_close", "gemini-cli.acp + gemini-cli.headless"): "upstream_unsupported",
    ("load_session", "gemini.live"): "operation_shape_not_applicable",
    ("resume_session", "gemini.live"): "operation_shape_not_applicable",
    ("native_session_close", "gemini.live"): "operation_shape_not_applicable",
    ("load_session", "llama-cpp.attached"): "operation_shape_not_applicable",
    ("resume_session", "llama-cpp.attached"): "operation_shape_not_applicable",
    ("native_session_close", "llama-cpp.attached"): "operation_shape_not_applicable",
    ("native_session_close", "kimi-code.acp + kimi-code.headless"): "upstream_unsupported",
    ("load_session", "kimi-code.local-server"): "upstream_unsupported",
    ("native_session_close", "kimi-code.local-server"): "upstream_unsupported",
    ("load_session", "kimi-platform.chat"): "operation_shape_not_applicable",
    ("resume_session", "kimi-platform.chat"): "operation_shape_not_applicable",
    ("native_session_close", "kimi-platform.chat"): "operation_shape_not_applicable",
    ("load_session", "ollama.attached"): "operation_shape_not_applicable",
    ("resume_session", "ollama.attached"): "operation_shape_not_applicable",
    ("native_session_close", "ollama.attached"): "operation_shape_not_applicable",
    ("native_session_close", "codex.app-server; codex.exec"): "upstream_unsupported",
    ("load_session", "openai.realtime"): "operation_shape_not_applicable",
    ("resume_session", "openai.realtime"): "operation_shape_not_applicable",
    ("native_session_close", "openai.realtime"): "operation_shape_not_applicable",
    ("load_session", "openai.background"): "operation_shape_not_applicable",
    ("resume_session", "openai.background"): "operation_shape_not_applicable",
    ("native_session_close", "openai.background"): "operation_shape_not_applicable",
    ("native_session_close", "opencode.http"): "upstream_unsupported",
    ("load_session", "xai.responses-websocket"): "operation_shape_not_applicable",
    ("resume_session", "xai.responses-websocket"): "operation_shape_not_applicable",
    ("native_session_close", "xai.responses-websocket"): "operation_shape_not_applicable",
    ("load_session", "grok-build.acp"): "contract_or_corpus_required",
    ("resume_session", "grok-build.acp"): "contract_or_corpus_required",
    ("native_session_close", "grok-build.acp"): "upstream_unsupported",
}
provider_retention_not_applicable = {
    "muse-code.headless",
    "cline.headless",
    "mistral-vibe.headless",
    "qoder.headless",
    "command-code.headless",
    "oh-my-pi.rpc",
    "qwen.headless",
    "bedrock.catalogue; bedrock.runtime",
    "claude-code.headless; claude-code.response-only",
    "anthropic.managed-agent",
    "anthropic.messages",
    "pi.rpc",
    "pi.sdk-sidecar",
    "deepseek.continuation",
    "deepseek-harness.jsonrpc",
    "zcode.app-server",
    "gemini.live",
    "llama-cpp.attached",
    "kimi-platform.chat",
    "ollama.attached",
    "openai.realtime",
    "xai.responses-websocket",
}
provider_session_not_applicable = provider_retention_not_applicable | {
    "openai.background",
}
owned_cleanup_not_applicable = (
    provider_retention_not_applicable
    - {"alibaba.conversations", "anthropic.managed-agent"}
) | {
    "antigravity.catalogue + antigravity.headless",
    "codex.app-server; codex.exec",
    "cursor-agent.catalogue + cursor-agent.acp + cursor-agent.headless",
}
provider_retention_classifications = {}
for feature in ["provider_session_archive", "provider_session_restore"]:
    for route in provider_session_not_applicable:
        provider_retention_classifications[(feature, route)] = (
            "operation_shape_not_applicable"
        )
    for route in [
        "antigravity.catalogue + antigravity.headless",
        "alibaba.conversations",
        "claude-agent.acp",
        "gemini-cli.acp + gemini-cli.headless",
        "grok-build.acp",
        "cline.acp",
        "copilot-cli.acp",
        "goose.acp",
        "kiro.acp",
        "deepagents.acp",
        "kimi-code.acp + kimi-code.headless",
        "opencode.http",
        "cursor-agent.catalogue + cursor-agent.acp + cursor-agent.headless",
    ]:
        provider_retention_classifications[(feature, route)] = "upstream_unsupported"
for route in provider_session_not_applicable:
    provider_retention_classifications[("provider_session_delete", route)] = (
        "operation_shape_not_applicable"
    )
for route in [
    "antigravity.catalogue + antigravity.headless",
    "grok-build.acp",
    "cline.acp",
    "copilot-cli.acp",
    "goose.acp",
    "kiro.acp",
    "deepagents.acp",
    "kimi-code.acp + kimi-code.headless",
    "kimi-code.local-server",
    "cursor-agent.catalogue + cursor-agent.acp + cursor-agent.headless",
]:
    provider_retention_classifications[("provider_session_delete", route)] = (
        "upstream_unsupported"
    )
provider_retention_classifications[
    ("provider_session_delete", "gemini-cli.acp + gemini-cli.headless")
] = "selected_surface_absence"
provider_retention_classifications[
    ("provider_session_delete", "alibaba.conversations")
] = "shared_contract_and_corpus_required"
for feature in ["provider_session_restore", "provider_session_delete"]:
    provider_retention_classifications[(feature, "deepseek-harness.local-server")] = (
        "selected_surface_absence"
    )
for route in owned_cleanup_not_applicable:
    provider_retention_classifications[("owned_remote_resource_cleanup", route)] = (
        "operation_shape_not_applicable"
    )
for route in [
    "grok-build.acp",
    "cline.acp",
    "copilot-cli.acp",
    "goose.acp",
    "kiro.acp",
    "deepagents.acp",
    "kimi-code.acp + kimi-code.headless",
    "kimi-code.local-server",
]:
    provider_retention_classifications[("owned_remote_resource_cleanup", route)] = (
        "upstream_unsupported"
    )
provider_retention_classifications[
    ("owned_remote_resource_cleanup", "gemini-cli.acp + gemini-cli.headless")
] = "separate_transport_and_corpus_required"
provider_retention_classifications[
    ("owned_remote_resource_cleanup", "claude-agent.acp")
] = "ready_existing_contract"
provider_retention_classifications[
    ("owned_remote_resource_cleanup", "openai.background")
] = "shared_contract_and_corpus_required"
provider_retention_classifications[
    ("owned_remote_resource_cleanup", "opencode.http")
] = "realized_matrix_false_negative"
