use super::ledger::*;

/// Deterministic disposition of exactly the 35 `codex.exec` census rows.
///
/// The ledger claims nothing about `codex.app-server` or any other route.
pub(super) const CODEX_EXEC_TRANCHE: [LedgerEntry; 35] = [
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "model-catalogue",
        semantic_id: "feature.model-catalogue",
        emitted_by: &[],
        withheld_because: "no prepared exec plan requires the model-catalogue capability",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "structured-run",
        semantic_id: "feature.structured-run",
        emitted_by: BOTH,
        withheld_because: "",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "interactive-session",
        semantic_id: "feature.interactive-session",
        emitted_by: &[],
        withheld_because: ONE_SHOT,
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "route-observation",
        semantic_id: "feature.streaming-events",
        emitted_by: BOTH,
        withheld_because: "",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "route-observation",
        semantic_id: "feature.usage-evidence",
        emitted_by: &[],
        withheld_because: "no prepared exec plan requires the usage-reporting capability",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "route-capability",
        semantic_id: "feature.reasoning-selection",
        emitted_by: OPTIONAL,
        withheld_because: "",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "route-capability",
        semantic_id: "feature.structured-output",
        emitted_by: OPTIONAL,
        withheld_because: "",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "route-capability",
        semantic_id: "feature.attachments",
        emitted_by: OPTIONAL,
        withheld_because: "",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "route-capability",
        semantic_id: "feature.consumer-tool-exchange",
        emitted_by: &[],
        withheld_because: TOOLS_REJECTED,
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "route-capability",
        semantic_id: "feature.question-exchange",
        emitted_by: &[],
        withheld_because: "no prepared exec plan carries a session access policy",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "route-capability",
        semantic_id: "feature.cancellation-or-interruption",
        emitted_by: &[],
        withheld_because: "no prepared exec plan requires the interruption capability",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "session-lifecycle",
        semantic_id: "feature.load-session",
        emitted_by: &[],
        withheld_because: ONE_SHOT,
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "session-lifecycle",
        semantic_id: "feature.resume-session",
        emitted_by: &[],
        withheld_because: ONE_SHOT,
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "session-lifecycle",
        semantic_id: "feature.provider-session-catalogue",
        emitted_by: &[],
        withheld_because: ONE_SHOT,
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "session-lifecycle",
        semantic_id: "feature.provider-session-import",
        emitted_by: &[],
        withheld_because: ONE_SHOT,
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "route-capability",
        semantic_id: "feature.working-resource",
        emitted_by: &[],
        withheld_because: "no prepared exec plan requires the working-resource capability",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "route-capability",
        semantic_id: "feature.bounded-workspace-text-write",
        emitted_by: &[],
        withheld_because: "no prepared exec plan requires the workspace text-write capability",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "route-capability",
        semantic_id: "feature.external-search",
        emitted_by: OPTIONAL,
        withheld_because: "",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "session-lifecycle",
        semantic_id: "feature.provider-session-archive",
        emitted_by: &[],
        withheld_because: ONE_SHOT,
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "session-lifecycle",
        semantic_id: "feature.provider-session-restore",
        emitted_by: &[],
        withheld_because: ONE_SHOT,
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "session-lifecycle",
        semantic_id: "feature.provider-session-delete",
        emitted_by: &[],
        withheld_because: ONE_SHOT,
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "session-lifecycle",
        semantic_id: "feature.persistent-session-posture",
        emitted_by: &[],
        withheld_because: "the census marks durable persistence not applicable to codex.exec",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "route-capability",
        semantic_id: "feature.prepared-facade",
        emitted_by: BOTH,
        withheld_because: "",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "route-observation",
        semantic_id: "feature.activity-observation",
        emitted_by: BOTH,
        withheld_because: "",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "structured-run",
        semantic_id: "control.model-selection",
        emitted_by: BOTH,
        withheld_because: "",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "structured-run",
        semantic_id: "control.reasoning-selection",
        emitted_by: OPTIONAL,
        withheld_because: "",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "structured-run",
        semantic_id: "control.maximum-output-tokens",
        emitted_by: &[],
        withheld_because: "the prepared exec request carries no output-token maximum",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "structured-run",
        semantic_id: "control.structured-output",
        emitted_by: OPTIONAL,
        withheld_because: "",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "structured-run",
        semantic_id: "control.attachments",
        emitted_by: OPTIONAL,
        withheld_because: "",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "structured-run",
        semantic_id: "control.external-network-policy",
        emitted_by: BOTH,
        withheld_because: "",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "structured-run",
        semantic_id: "control.external-search-policy",
        emitted_by: BOTH,
        withheld_because: "",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "structured-run",
        semantic_id: "control.model-verbosity",
        emitted_by: OPTIONAL,
        withheld_because: "",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "structured-run",
        semantic_id: "control.tool-declarations",
        emitted_by: &[],
        withheld_because: TOOLS_REJECTED,
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "session-management",
        semantic_id: "control.load-session",
        emitted_by: &[],
        withheld_because: "no public prepared exec session-load operation exists",
    },
    LedgerEntry {
        route_id: EXEC_ROUTE,
        operation_shape: "session-management",
        semantic_id: "control.resume-session",
        emitted_by: &[],
        withheld_because: "no public prepared exec session-resume operation exists",
    },
];
