use serde_json::Value;
use std::collections::BTreeSet;

const PROTOCOL: &str = include_str!("fixtures/claude-agent-acp-0.81.2/protocol.json");
const DIST_INVENTORY: &str = include_str!("fixtures/claude-agent-acp-0.81.2/dist-inventory.json");

const UNMAPPED_0_80_0_KEYS: &[&str] = &[
    "acp_sdk_pin_1_4_0_to_1_5_0",
    "acp_sdk_schema_protocol_version_stays_1",
    "agent_sdk_pin_0_3_274_to_0_3_278",
    "do_not_flatten_to_claude_agent_sdk_family",
    "cancel_optional_compaction_interrupt_noop_without_session_compaction",
    "swallowtail_does_not_advertise_session_compaction",
    "query_interrupt_await_still_unbounded",
    "close_teardown_close_query_stream_identical",
    "mcp_servers_http_mapping_identical",
];

const UNMAPPED_0_81_0_KEYS: &[&str] = &[
    "session_notices_gated_on_client_session_notices",
    "swallowtail_does_not_advertise_session_notices",
    "notice_fallback_is_already_mapped_agent_message_chunk",
    "agent_sdk_pin_0_3_278_to_0_3_280",
    "do_not_flatten_to_claude_code_or_sdk_family",
    "acp_sdk_stays_1_5_0",
];

const UNMAPPED_0_81_1_KEYS: &[&str] = &[
    "managed_policy_env_extract_unmapped",
    "usage_model_rides_in_underscore_meta",
    "unknown_underscore_notifications_ignored",
    "plan_approval_bypass_option_unmapped",
    "acp_sdk_stays_1_5_0",
    "agent_sdk_stays_0_3_280",
];

const UNMAPPED_0_81_2_KEYS: &[&str] = &[
    "native_subagent_resume_announcement_unmapped",
    "clear_context_plan_followup_unmapped",
    "acp_sdk_stays_1_5_0",
    "agent_sdk_stays_0_3_280",
];

const SELECTED_COMPATIBLE_BECAUSE_KEYS: &[&str] = &[
    "explicit_set_config_option_model_then_confirm_model",
    "explicit_set_config_option_effort_then_confirm_reasoning",
    "session_new_display_seed_is_not_the_confirmation_path",
    "config_option_ids_and_categories_unchanged",
    "permission_option_kinds_unchanged",
    "usage_invariant_unchanged",
    "stopReason_domain_and_catchall_unchanged",
    "cancel_still_session_cancel",
    "unknown_session_updates_ignored",
    "unknown_underscore_notifications_ignored",
    "acp_wire_protocol_version_unchanged",
    "agent_sdk_pin_unmapped",
    "compaction_update_not_advertised_so_not_emitted_on_selected_route",
    "session_notices_not_advertised_so_notice_kind_not_emitted_on_selected_route",
    "elicitation_form_keys_and_other_title_unchanged",
    "close_teardown_and_mcp_http_mapping_unchanged",
];

const FROM_0_79_TO_0_80_CHANGED: &[&str] = &[
    "dist/acp-agent.d.ts",
    "dist/acp-agent.d.ts.map",
    "dist/acp-agent.js",
    "dist/context-compaction.d.ts",
    "dist/context-compaction.d.ts.map",
    "dist/context-compaction.js",
    "dist/tools.d.ts",
    "dist/tools.d.ts.map",
    "dist/tools.js",
    "package.json",
];

const FROM_0_80_TO_0_81_ADDED: &[&str] = &[
    "dist/session-notices.d.ts",
    "dist/session-notices.d.ts.map",
    "dist/session-notices.js",
];

const FROM_0_80_TO_0_81_CHANGED: &[&str] = &[
    "dist/acp-agent.d.ts",
    "dist/acp-agent.d.ts.map",
    "dist/acp-agent.js",
    "dist/async-tasks.d.ts",
    "dist/async-tasks.d.ts.map",
    "dist/async-tasks.js",
    "dist/session-mode.d.ts",
    "dist/session-mode.d.ts.map",
    "dist/session-mode.js",
    "package.json",
];

const FROM_0_81_0_TO_0_81_1_ADDED: &[&str] = &[
    "dist/managed-policy.d.ts",
    "dist/managed-policy.d.ts.map",
    "dist/managed-policy.js",
];

const FROM_0_81_0_TO_0_81_1_CHANGED: &[&str] = &[
    "dist/acp-agent.d.ts",
    "dist/acp-agent.d.ts.map",
    "dist/acp-agent.js",
    "dist/index.js",
    "dist/permissions/options/shared.d.ts",
    "dist/permissions/options/shared.d.ts.map",
    "dist/permissions/options/tools.d.ts.map",
    "dist/permissions/options/tools.js",
    "dist/session-mode.d.ts",
    "dist/session-mode.d.ts.map",
    "dist/session-mode.js",
    "dist/session-notices.d.ts",
    "dist/session-notices.d.ts.map",
    "dist/session-notices.js",
    "dist/tools.d.ts.map",
    "dist/tools.js",
    "package.json",
];

const FROM_0_81_1_TO_0_81_2_CHANGED: &[&str] = &[
    "dist/acp-agent.d.ts.map",
    "dist/acp-agent.js",
    "dist/exit-plan.d.ts",
    "dist/exit-plan.d.ts.map",
    "dist/exit-plan.js",
    "dist/native-subagents.d.ts",
    "dist/native-subagents.d.ts.map",
    "dist/native-subagents.js",
    "package.json",
];

const IDENTICAL_THROUGH_ALL_HOPS: &[&str] = &[
    "LICENSE",
    "README.md",
    "dist/acp-subagents.d.ts",
    "dist/acp-subagents.d.ts.map",
    "dist/acp-subagents.js",
    "dist/air-extension.d.ts",
    "dist/air-extension.d.ts.map",
    "dist/air-extension.js",
    "dist/auth-status.d.ts",
    "dist/auth-status.d.ts.map",
    "dist/auth-status.js",
    "dist/clear-context-coordinator.d.ts",
    "dist/clear-context-coordinator.d.ts.map",
    "dist/clear-context-coordinator.js",
    "dist/context-compaction-meta.d.ts",
    "dist/context-compaction-meta.d.ts.map",
    "dist/context-compaction-meta.js",
    "dist/diff.d.ts",
    "dist/diff.d.ts.map",
    "dist/diff.js",
    "dist/elicitation.d.ts",
    "dist/elicitation.d.ts.map",
    "dist/elicitation.js",
    "dist/file-change-audit.d.ts",
    "dist/file-change-audit.d.ts.map",
    "dist/file-change-audit.js",
    "dist/fork-session.d.ts",
    "dist/fork-session.d.ts.map",
    "dist/fork-session.js",
    "dist/goal-extension.d.ts",
    "dist/goal-extension.d.ts.map",
    "dist/goal-extension.js",
    "dist/hide-claude-auth.d.ts",
    "dist/hide-claude-auth.d.ts.map",
    "dist/hide-claude-auth.js",
    "dist/index.d.ts",
    "dist/index.d.ts.map",
    "dist/lib.d.ts",
    "dist/lib.d.ts.map",
    "dist/lib.js",
    "dist/permissions/effects.d.ts",
    "dist/permissions/effects.d.ts.map",
    "dist/permissions/effects.js",
    "dist/permissions/modes.d.ts",
    "dist/permissions/modes.d.ts.map",
    "dist/permissions/modes.js",
    "dist/permissions/normalization.d.ts",
    "dist/permissions/normalization.d.ts.map",
    "dist/permissions/normalization.js",
    "dist/permissions/options.d.ts",
    "dist/permissions/options.d.ts.map",
    "dist/permissions/options.js",
    "dist/permissions/options/filesystem.d.ts",
    "dist/permissions/options/filesystem.d.ts.map",
    "dist/permissions/options/filesystem.js",
    "dist/permissions/options/shared.js",
    "dist/permissions/options/shell.d.ts",
    "dist/permissions/options/shell.d.ts.map",
    "dist/permissions/options/shell.js",
    "dist/permissions/options/tools.d.ts",
    "dist/permissions/presentation.d.ts",
    "dist/permissions/presentation.d.ts.map",
    "dist/permissions/presentation.js",
    "dist/permissions/response.d.ts",
    "dist/permissions/response.d.ts.map",
    "dist/permissions/response.js",
    "dist/resumed-session.d.ts",
    "dist/resumed-session.d.ts.map",
    "dist/resumed-session.js",
    "dist/session-config-ids.d.ts",
    "dist/session-config-ids.d.ts.map",
    "dist/session-config-ids.js",
    "dist/session-effort.d.ts",
    "dist/session-effort.d.ts.map",
    "dist/session-effort.js",
    "dist/session-failure-extension.d.ts",
    "dist/session-failure-extension.d.ts.map",
    "dist/session-failure-extension.js",
    "dist/session-model.d.ts",
    "dist/session-model.d.ts.map",
    "dist/session-model.js",
    "dist/session-timing.d.ts",
    "dist/session-timing.d.ts.map",
    "dist/session-timing.js",
    "dist/session-titles.d.ts",
    "dist/session-titles.d.ts.map",
    "dist/session-titles.js",
    "dist/settings.d.ts",
    "dist/settings.d.ts.map",
    "dist/settings.js",
    "dist/tool-result-meta.d.ts",
    "dist/tool-result-meta.d.ts.map",
    "dist/tool-result-meta.js",
    "dist/usage-markdown.d.ts",
    "dist/usage-markdown.d.ts.map",
    "dist/usage-markdown.js",
    "dist/utils.d.ts",
    "dist/utils.d.ts.map",
    "dist/utils.js",
];

const FROM_0_79_TO_0_80_IDENTICAL: &[&str] = &[
    "LICENSE",
    "README.md",
    "dist/acp-subagents.d.ts",
    "dist/acp-subagents.d.ts.map",
    "dist/acp-subagents.js",
    "dist/air-extension.d.ts",
    "dist/air-extension.d.ts.map",
    "dist/air-extension.js",
    "dist/async-tasks.d.ts",
    "dist/async-tasks.d.ts.map",
    "dist/async-tasks.js",
    "dist/auth-status.d.ts",
    "dist/auth-status.d.ts.map",
    "dist/auth-status.js",
    "dist/clear-context-coordinator.d.ts",
    "dist/clear-context-coordinator.d.ts.map",
    "dist/clear-context-coordinator.js",
    "dist/context-compaction-meta.d.ts",
    "dist/context-compaction-meta.d.ts.map",
    "dist/context-compaction-meta.js",
    "dist/diff.d.ts",
    "dist/diff.d.ts.map",
    "dist/diff.js",
    "dist/elicitation.d.ts",
    "dist/elicitation.d.ts.map",
    "dist/elicitation.js",
    "dist/exit-plan.d.ts",
    "dist/exit-plan.d.ts.map",
    "dist/exit-plan.js",
    "dist/file-change-audit.d.ts",
    "dist/file-change-audit.d.ts.map",
    "dist/file-change-audit.js",
    "dist/fork-session.d.ts",
    "dist/fork-session.d.ts.map",
    "dist/fork-session.js",
    "dist/goal-extension.d.ts",
    "dist/goal-extension.d.ts.map",
    "dist/goal-extension.js",
    "dist/hide-claude-auth.d.ts",
    "dist/hide-claude-auth.d.ts.map",
    "dist/hide-claude-auth.js",
    "dist/index.d.ts",
    "dist/index.d.ts.map",
    "dist/index.js",
    "dist/lib.d.ts",
    "dist/lib.d.ts.map",
    "dist/lib.js",
    "dist/native-subagents.d.ts",
    "dist/native-subagents.d.ts.map",
    "dist/native-subagents.js",
    "dist/permissions/effects.d.ts",
    "dist/permissions/effects.d.ts.map",
    "dist/permissions/effects.js",
    "dist/permissions/modes.d.ts",
    "dist/permissions/modes.d.ts.map",
    "dist/permissions/modes.js",
    "dist/permissions/normalization.d.ts",
    "dist/permissions/normalization.d.ts.map",
    "dist/permissions/normalization.js",
    "dist/permissions/options.d.ts",
    "dist/permissions/options.d.ts.map",
    "dist/permissions/options.js",
    "dist/permissions/options/filesystem.d.ts",
    "dist/permissions/options/filesystem.d.ts.map",
    "dist/permissions/options/filesystem.js",
    "dist/permissions/options/shared.d.ts",
    "dist/permissions/options/shared.d.ts.map",
    "dist/permissions/options/shared.js",
    "dist/permissions/options/shell.d.ts",
    "dist/permissions/options/shell.d.ts.map",
    "dist/permissions/options/shell.js",
    "dist/permissions/options/tools.d.ts",
    "dist/permissions/options/tools.d.ts.map",
    "dist/permissions/options/tools.js",
    "dist/permissions/presentation.d.ts",
    "dist/permissions/presentation.d.ts.map",
    "dist/permissions/presentation.js",
    "dist/permissions/response.d.ts",
    "dist/permissions/response.d.ts.map",
    "dist/permissions/response.js",
    "dist/resumed-session.d.ts",
    "dist/resumed-session.d.ts.map",
    "dist/resumed-session.js",
    "dist/session-config-ids.d.ts",
    "dist/session-config-ids.d.ts.map",
    "dist/session-config-ids.js",
    "dist/session-effort.d.ts",
    "dist/session-effort.d.ts.map",
    "dist/session-effort.js",
    "dist/session-failure-extension.d.ts",
    "dist/session-failure-extension.d.ts.map",
    "dist/session-failure-extension.js",
    "dist/session-mode.d.ts",
    "dist/session-mode.d.ts.map",
    "dist/session-mode.js",
    "dist/session-model.d.ts",
    "dist/session-model.d.ts.map",
    "dist/session-model.js",
    "dist/session-timing.d.ts",
    "dist/session-timing.d.ts.map",
    "dist/session-timing.js",
    "dist/session-titles.d.ts",
    "dist/session-titles.d.ts.map",
    "dist/session-titles.js",
    "dist/settings.d.ts",
    "dist/settings.d.ts.map",
    "dist/settings.js",
    "dist/tool-result-meta.d.ts",
    "dist/tool-result-meta.d.ts.map",
    "dist/tool-result-meta.js",
    "dist/usage-markdown.d.ts",
    "dist/usage-markdown.d.ts.map",
    "dist/usage-markdown.js",
    "dist/utils.d.ts",
    "dist/utils.d.ts.map",
    "dist/utils.js",
];

const FROM_0_80_TO_0_81_IDENTICAL: &[&str] = &[
    "LICENSE",
    "README.md",
    "dist/acp-subagents.d.ts",
    "dist/acp-subagents.d.ts.map",
    "dist/acp-subagents.js",
    "dist/air-extension.d.ts",
    "dist/air-extension.d.ts.map",
    "dist/air-extension.js",
    "dist/auth-status.d.ts",
    "dist/auth-status.d.ts.map",
    "dist/auth-status.js",
    "dist/clear-context-coordinator.d.ts",
    "dist/clear-context-coordinator.d.ts.map",
    "dist/clear-context-coordinator.js",
    "dist/context-compaction-meta.d.ts",
    "dist/context-compaction-meta.d.ts.map",
    "dist/context-compaction-meta.js",
    "dist/context-compaction.d.ts",
    "dist/context-compaction.d.ts.map",
    "dist/context-compaction.js",
    "dist/diff.d.ts",
    "dist/diff.d.ts.map",
    "dist/diff.js",
    "dist/elicitation.d.ts",
    "dist/elicitation.d.ts.map",
    "dist/elicitation.js",
    "dist/exit-plan.d.ts",
    "dist/exit-plan.d.ts.map",
    "dist/exit-plan.js",
    "dist/file-change-audit.d.ts",
    "dist/file-change-audit.d.ts.map",
    "dist/file-change-audit.js",
    "dist/fork-session.d.ts",
    "dist/fork-session.d.ts.map",
    "dist/fork-session.js",
    "dist/goal-extension.d.ts",
    "dist/goal-extension.d.ts.map",
    "dist/goal-extension.js",
    "dist/hide-claude-auth.d.ts",
    "dist/hide-claude-auth.d.ts.map",
    "dist/hide-claude-auth.js",
    "dist/index.d.ts",
    "dist/index.d.ts.map",
    "dist/index.js",
    "dist/lib.d.ts",
    "dist/lib.d.ts.map",
    "dist/lib.js",
    "dist/native-subagents.d.ts",
    "dist/native-subagents.d.ts.map",
    "dist/native-subagents.js",
    "dist/permissions/effects.d.ts",
    "dist/permissions/effects.d.ts.map",
    "dist/permissions/effects.js",
    "dist/permissions/modes.d.ts",
    "dist/permissions/modes.d.ts.map",
    "dist/permissions/modes.js",
    "dist/permissions/normalization.d.ts",
    "dist/permissions/normalization.d.ts.map",
    "dist/permissions/normalization.js",
    "dist/permissions/options.d.ts",
    "dist/permissions/options.d.ts.map",
    "dist/permissions/options.js",
    "dist/permissions/options/filesystem.d.ts",
    "dist/permissions/options/filesystem.d.ts.map",
    "dist/permissions/options/filesystem.js",
    "dist/permissions/options/shared.d.ts",
    "dist/permissions/options/shared.d.ts.map",
    "dist/permissions/options/shared.js",
    "dist/permissions/options/shell.d.ts",
    "dist/permissions/options/shell.d.ts.map",
    "dist/permissions/options/shell.js",
    "dist/permissions/options/tools.d.ts",
    "dist/permissions/options/tools.d.ts.map",
    "dist/permissions/options/tools.js",
    "dist/permissions/presentation.d.ts",
    "dist/permissions/presentation.d.ts.map",
    "dist/permissions/presentation.js",
    "dist/permissions/response.d.ts",
    "dist/permissions/response.d.ts.map",
    "dist/permissions/response.js",
    "dist/resumed-session.d.ts",
    "dist/resumed-session.d.ts.map",
    "dist/resumed-session.js",
    "dist/session-config-ids.d.ts",
    "dist/session-config-ids.d.ts.map",
    "dist/session-config-ids.js",
    "dist/session-effort.d.ts",
    "dist/session-effort.d.ts.map",
    "dist/session-effort.js",
    "dist/session-failure-extension.d.ts",
    "dist/session-failure-extension.d.ts.map",
    "dist/session-failure-extension.js",
    "dist/session-model.d.ts",
    "dist/session-model.d.ts.map",
    "dist/session-model.js",
    "dist/session-timing.d.ts",
    "dist/session-timing.d.ts.map",
    "dist/session-timing.js",
    "dist/session-titles.d.ts",
    "dist/session-titles.d.ts.map",
    "dist/session-titles.js",
    "dist/settings.d.ts",
    "dist/settings.d.ts.map",
    "dist/settings.js",
    "dist/tool-result-meta.d.ts",
    "dist/tool-result-meta.d.ts.map",
    "dist/tool-result-meta.js",
    "dist/tools.d.ts",
    "dist/tools.d.ts.map",
    "dist/tools.js",
    "dist/usage-markdown.d.ts",
    "dist/usage-markdown.d.ts.map",
    "dist/usage-markdown.js",
    "dist/utils.d.ts",
    "dist/utils.d.ts.map",
    "dist/utils.js",
];

const FROM_0_81_0_TO_0_81_1_IDENTICAL: &[&str] = &[
    "LICENSE",
    "README.md",
    "dist/acp-subagents.d.ts",
    "dist/acp-subagents.d.ts.map",
    "dist/acp-subagents.js",
    "dist/air-extension.d.ts",
    "dist/air-extension.d.ts.map",
    "dist/air-extension.js",
    "dist/async-tasks.d.ts",
    "dist/async-tasks.d.ts.map",
    "dist/async-tasks.js",
    "dist/auth-status.d.ts",
    "dist/auth-status.d.ts.map",
    "dist/auth-status.js",
    "dist/clear-context-coordinator.d.ts",
    "dist/clear-context-coordinator.d.ts.map",
    "dist/clear-context-coordinator.js",
    "dist/context-compaction-meta.d.ts",
    "dist/context-compaction-meta.d.ts.map",
    "dist/context-compaction-meta.js",
    "dist/context-compaction.d.ts",
    "dist/context-compaction.d.ts.map",
    "dist/context-compaction.js",
    "dist/diff.d.ts",
    "dist/diff.d.ts.map",
    "dist/diff.js",
    "dist/elicitation.d.ts",
    "dist/elicitation.d.ts.map",
    "dist/elicitation.js",
    "dist/exit-plan.d.ts",
    "dist/exit-plan.d.ts.map",
    "dist/exit-plan.js",
    "dist/file-change-audit.d.ts",
    "dist/file-change-audit.d.ts.map",
    "dist/file-change-audit.js",
    "dist/fork-session.d.ts",
    "dist/fork-session.d.ts.map",
    "dist/fork-session.js",
    "dist/goal-extension.d.ts",
    "dist/goal-extension.d.ts.map",
    "dist/goal-extension.js",
    "dist/hide-claude-auth.d.ts",
    "dist/hide-claude-auth.d.ts.map",
    "dist/hide-claude-auth.js",
    "dist/index.d.ts",
    "dist/index.d.ts.map",
    "dist/lib.d.ts",
    "dist/lib.d.ts.map",
    "dist/lib.js",
    "dist/native-subagents.d.ts",
    "dist/native-subagents.d.ts.map",
    "dist/native-subagents.js",
    "dist/permissions/effects.d.ts",
    "dist/permissions/effects.d.ts.map",
    "dist/permissions/effects.js",
    "dist/permissions/modes.d.ts",
    "dist/permissions/modes.d.ts.map",
    "dist/permissions/modes.js",
    "dist/permissions/normalization.d.ts",
    "dist/permissions/normalization.d.ts.map",
    "dist/permissions/normalization.js",
    "dist/permissions/options.d.ts",
    "dist/permissions/options.d.ts.map",
    "dist/permissions/options.js",
    "dist/permissions/options/filesystem.d.ts",
    "dist/permissions/options/filesystem.d.ts.map",
    "dist/permissions/options/filesystem.js",
    "dist/permissions/options/shared.js",
    "dist/permissions/options/shell.d.ts",
    "dist/permissions/options/shell.d.ts.map",
    "dist/permissions/options/shell.js",
    "dist/permissions/options/tools.d.ts",
    "dist/permissions/presentation.d.ts",
    "dist/permissions/presentation.d.ts.map",
    "dist/permissions/presentation.js",
    "dist/permissions/response.d.ts",
    "dist/permissions/response.d.ts.map",
    "dist/permissions/response.js",
    "dist/resumed-session.d.ts",
    "dist/resumed-session.d.ts.map",
    "dist/resumed-session.js",
    "dist/session-config-ids.d.ts",
    "dist/session-config-ids.d.ts.map",
    "dist/session-config-ids.js",
    "dist/session-effort.d.ts",
    "dist/session-effort.d.ts.map",
    "dist/session-effort.js",
    "dist/session-failure-extension.d.ts",
    "dist/session-failure-extension.d.ts.map",
    "dist/session-failure-extension.js",
    "dist/session-model.d.ts",
    "dist/session-model.d.ts.map",
    "dist/session-model.js",
    "dist/session-timing.d.ts",
    "dist/session-timing.d.ts.map",
    "dist/session-timing.js",
    "dist/session-titles.d.ts",
    "dist/session-titles.d.ts.map",
    "dist/session-titles.js",
    "dist/settings.d.ts",
    "dist/settings.d.ts.map",
    "dist/settings.js",
    "dist/tool-result-meta.d.ts",
    "dist/tool-result-meta.d.ts.map",
    "dist/tool-result-meta.js",
    "dist/tools.d.ts",
    "dist/usage-markdown.d.ts",
    "dist/usage-markdown.d.ts.map",
    "dist/usage-markdown.js",
    "dist/utils.d.ts",
    "dist/utils.d.ts.map",
    "dist/utils.js",
];

const FROM_0_81_1_TO_0_81_2_IDENTICAL: &[&str] = &[
    "LICENSE",
    "README.md",
    "dist/acp-agent.d.ts",
    "dist/acp-subagents.d.ts",
    "dist/acp-subagents.d.ts.map",
    "dist/acp-subagents.js",
    "dist/air-extension.d.ts",
    "dist/air-extension.d.ts.map",
    "dist/air-extension.js",
    "dist/async-tasks.d.ts",
    "dist/async-tasks.d.ts.map",
    "dist/async-tasks.js",
    "dist/auth-status.d.ts",
    "dist/auth-status.d.ts.map",
    "dist/auth-status.js",
    "dist/clear-context-coordinator.d.ts",
    "dist/clear-context-coordinator.d.ts.map",
    "dist/clear-context-coordinator.js",
    "dist/context-compaction-meta.d.ts",
    "dist/context-compaction-meta.d.ts.map",
    "dist/context-compaction-meta.js",
    "dist/context-compaction.d.ts",
    "dist/context-compaction.d.ts.map",
    "dist/context-compaction.js",
    "dist/diff.d.ts",
    "dist/diff.d.ts.map",
    "dist/diff.js",
    "dist/elicitation.d.ts",
    "dist/elicitation.d.ts.map",
    "dist/elicitation.js",
    "dist/file-change-audit.d.ts",
    "dist/file-change-audit.d.ts.map",
    "dist/file-change-audit.js",
    "dist/fork-session.d.ts",
    "dist/fork-session.d.ts.map",
    "dist/fork-session.js",
    "dist/goal-extension.d.ts",
    "dist/goal-extension.d.ts.map",
    "dist/goal-extension.js",
    "dist/hide-claude-auth.d.ts",
    "dist/hide-claude-auth.d.ts.map",
    "dist/hide-claude-auth.js",
    "dist/index.d.ts",
    "dist/index.d.ts.map",
    "dist/index.js",
    "dist/lib.d.ts",
    "dist/lib.d.ts.map",
    "dist/lib.js",
    "dist/managed-policy.d.ts",
    "dist/managed-policy.d.ts.map",
    "dist/managed-policy.js",
    "dist/permissions/effects.d.ts",
    "dist/permissions/effects.d.ts.map",
    "dist/permissions/effects.js",
    "dist/permissions/modes.d.ts",
    "dist/permissions/modes.d.ts.map",
    "dist/permissions/modes.js",
    "dist/permissions/normalization.d.ts",
    "dist/permissions/normalization.d.ts.map",
    "dist/permissions/normalization.js",
    "dist/permissions/options.d.ts",
    "dist/permissions/options.d.ts.map",
    "dist/permissions/options.js",
    "dist/permissions/options/filesystem.d.ts",
    "dist/permissions/options/filesystem.d.ts.map",
    "dist/permissions/options/filesystem.js",
    "dist/permissions/options/shared.d.ts",
    "dist/permissions/options/shared.d.ts.map",
    "dist/permissions/options/shared.js",
    "dist/permissions/options/shell.d.ts",
    "dist/permissions/options/shell.d.ts.map",
    "dist/permissions/options/shell.js",
    "dist/permissions/options/tools.d.ts",
    "dist/permissions/options/tools.d.ts.map",
    "dist/permissions/options/tools.js",
    "dist/permissions/presentation.d.ts",
    "dist/permissions/presentation.d.ts.map",
    "dist/permissions/presentation.js",
    "dist/permissions/response.d.ts",
    "dist/permissions/response.d.ts.map",
    "dist/permissions/response.js",
    "dist/resumed-session.d.ts",
    "dist/resumed-session.d.ts.map",
    "dist/resumed-session.js",
    "dist/session-config-ids.d.ts",
    "dist/session-config-ids.d.ts.map",
    "dist/session-config-ids.js",
    "dist/session-effort.d.ts",
    "dist/session-effort.d.ts.map",
    "dist/session-effort.js",
    "dist/session-failure-extension.d.ts",
    "dist/session-failure-extension.d.ts.map",
    "dist/session-failure-extension.js",
    "dist/session-mode.d.ts",
    "dist/session-mode.d.ts.map",
    "dist/session-mode.js",
    "dist/session-model.d.ts",
    "dist/session-model.d.ts.map",
    "dist/session-model.js",
    "dist/session-notices.d.ts",
    "dist/session-notices.d.ts.map",
    "dist/session-notices.js",
    "dist/session-timing.d.ts",
    "dist/session-timing.d.ts.map",
    "dist/session-timing.js",
    "dist/session-titles.d.ts",
    "dist/session-titles.d.ts.map",
    "dist/session-titles.js",
    "dist/settings.d.ts",
    "dist/settings.d.ts.map",
    "dist/settings.js",
    "dist/tool-result-meta.d.ts",
    "dist/tool-result-meta.d.ts.map",
    "dist/tool-result-meta.js",
    "dist/tools.d.ts",
    "dist/tools.d.ts.map",
    "dist/tools.js",
    "dist/usage-markdown.d.ts",
    "dist/usage-markdown.d.ts.map",
    "dist/usage-markdown.js",
    "dist/utils.d.ts",
    "dist/utils.d.ts.map",
    "dist/utils.js",
];

#[test]
fn identity_delta_ledger_is_mutation_sensitive() {
    let protocol: Value =
        serde_json::from_str(PROTOCOL).expect("Claude Agent 0.81.2 protocol corpus is valid JSON");
    let inventory: Value = serde_json::from_str(DIST_INVENTORY)
        .expect("Claude Agent 0.81.2 dist inventory is valid JSON");

    assert_eq!(protocol["mode_option_id_unchanged"], "mode");
    assert_eq!(protocol["mode_option_category_unchanged"], "mode");
    assert_eq!(protocol["plan_and_acceptEdits_still_advertised"], true);
    assert_eq!(protocol["effort_option_id_unchanged"], "effort");
    assert_eq!(
        protocol["effort_option_category_unchanged"],
        "thought_level"
    );
    assert_eq!(
        protocol["permission_kinds_unchanged"],
        serde_json::json!(["allow_once", "allow_always", "reject_once"])
    );
    assert_eq!(
        protocol["prompt_usage_fields_unchanged"],
        serde_json::json!([
            "inputTokens",
            "outputTokens",
            "cachedReadTokens",
            "cachedWriteTokens",
            "totalTokens"
        ])
    );
    assert_eq!(protocol["cancel_still_session_cancel"], true);
    assert_eq!(
        protocol["set_config_option_response_still_config_options"],
        true
    );
    assert_eq!(protocol["acp_sdk_0_80_0_through_0_81_2"], "1.5.0");
    assert_eq!(
        protocol["session_capabilities_required_by_adapter"],
        serde_json::json!(["close", "delete", "resume"])
    );
    assert_eq!(
        protocol["new_session_update_kinds_emitted_without_notices_capability"],
        serde_json::json!([])
    );
    assert_eq!(
        protocol["close_session_identical_0_79_0_through_0_81_2"],
        true
    );
    assert_eq!(
        protocol["mcp_servers_http_mapping_identical_0_79_0_through_0_81_2"],
        true
    );
    assert_eq!(protocol["http_mcp_honouring_stays_exact_0_79_0"], true);
    assert_true_object(&protocol["unmapped_0_80_0"], UNMAPPED_0_80_0_KEYS);
    assert_true_object(&protocol["unmapped_0_81_0"], UNMAPPED_0_81_0_KEYS);
    assert_true_object(&protocol["unmapped_0_81_1"], UNMAPPED_0_81_1_KEYS);
    assert_true_object(&protocol["unmapped_0_81_2"], UNMAPPED_0_81_2_KEYS);
    assert_true_object(
        &protocol["selected_compatible_because"],
        SELECTED_COMPATIBLE_BECAUSE_KEYS,
    );
    assert_eq!(
        protocol["acp_agent_js_byte_identical_0_79_0_through_0_81_2"],
        false
    );
    assert_eq!(
        protocol["elicitation_js_byte_identical_0_78_0_through_0_81_2"],
        true
    );

    assert_eq!(inventory["not_a_complete_semantic_changelog"], true);
    assert_eq!(
        inventory["package_file_counts"],
        serde_json::json!({
            "0.79.0": 126,
            "0.80.0": 126,
            "0.81.0": 129,
            "0.81.1": 132,
            "0.81.2": 132
        })
    );
    assert_exact_string_set(
        &inventory["from_0_79_0_to_0_80_0"]["changed"],
        FROM_0_79_TO_0_80_CHANGED,
    );
    assert_exact_string_set(
        &inventory["from_0_80_0_to_0_81_0"]["added"],
        FROM_0_80_TO_0_81_ADDED,
    );
    assert_exact_string_set(
        &inventory["from_0_80_0_to_0_81_0"]["changed"],
        FROM_0_80_TO_0_81_CHANGED,
    );
    assert_exact_string_set(
        &inventory["from_0_81_0_to_0_81_1"]["added"],
        FROM_0_81_0_TO_0_81_1_ADDED,
    );
    assert_exact_string_set(
        &inventory["from_0_81_0_to_0_81_1"]["changed"],
        FROM_0_81_0_TO_0_81_1_CHANGED,
    );
    assert_exact_string_set(
        &inventory["from_0_81_1_to_0_81_2"]["changed"],
        FROM_0_81_1_TO_0_81_2_CHANGED,
    );
    for hop in [
        "from_0_79_0_to_0_80_0",
        "from_0_80_0_to_0_81_0",
        "from_0_81_0_to_0_81_1",
        "from_0_81_1_to_0_81_2",
    ] {
        assert_eq!(inventory[hop]["removed"], serde_json::json!([]));
    }
    assert_eq!(
        inventory["from_0_79_0_to_0_80_0"]["added"],
        serde_json::json!([])
    );
    assert_eq!(
        inventory["from_0_81_1_to_0_81_2"]["added"],
        serde_json::json!([])
    );
    assert_exact_string_set(
        &inventory["identical_through_0_79_0_0_80_0_0_81_0_0_81_1_0_81_2"],
        IDENTICAL_THROUGH_ALL_HOPS,
    );
    assert_exact_string_set(
        &inventory["from_0_79_0_to_0_80_0"]["identical"],
        FROM_0_79_TO_0_80_IDENTICAL,
    );
    assert_exact_string_set(
        &inventory["from_0_80_0_to_0_81_0"]["identical"],
        FROM_0_80_TO_0_81_IDENTICAL,
    );
    assert_exact_string_set(
        &inventory["from_0_81_0_to_0_81_1"]["identical"],
        FROM_0_81_0_TO_0_81_1_IDENTICAL,
    );
    assert_exact_string_set(
        &inventory["from_0_81_1_to_0_81_2"]["identical"],
        FROM_0_81_1_TO_0_81_2_IDENTICAL,
    );
    for path in [
        "dist/elicitation.js",
        "dist/settings.js",
        "dist/utils.js",
        "dist/lib.js",
        "dist/session-config-ids.js",
    ] {
        let hashes = inventory["hashes"][path]
            .as_object()
            .expect("per-version hash object");
        assert_eq!(hashes.len(), 5, "{path}");
        assert_eq!(
            hashes
                .values()
                .map(|value| value.as_str().expect("hash string"))
                .collect::<BTreeSet<_>>()
                .len(),
            1,
            "{path} must be byte-identical across every compared hop"
        );
    }
    assert_eq!(
        inventory["hashes"]["dist/index.js"]["0.79.0"],
        inventory["hashes"]["dist/index.js"]["0.81.0"]
    );
    assert_ne!(
        inventory["hashes"]["dist/index.js"]["0.81.0"],
        inventory["hashes"]["dist/index.js"]["0.81.1"]
    );
    assert_eq!(
        inventory["hashes"]["dist/index.js"]["0.81.1"],
        inventory["hashes"]["dist/index.js"]["0.81.2"]
    );
    assert_eq!(
        inventory["hashes"]["dist/acp-agent.js"]["0.79.0"],
        "e9711af5c5dd150718c4a22b1760f913ce8a871b7355d1f0f63aa845d282e37c"
    );
    assert_eq!(
        inventory["hashes"]["dist/acp-agent.js"]["0.81.2"],
        "36a33a984624541ea013c085f5bd1d982294cfe70beb42826752f62bdc538d64"
    );
    assert_eq!(
        inventory["hashes"]["dist/elicitation.js"]["0.79.0"],
        inventory["hashes"]["dist/elicitation.js"]["0.81.2"]
    );
    assert_eq!(
        inventory["hashes"]["package.json"]["0.79.0"],
        "9f6cefab78ff1a788f155e857509ac57d11564aaab6183c9d976a77b858f2558"
    );
    assert_eq!(
        inventory["named_unmapped_with_reason"]["0.81.0_added_modules"][0]["path"],
        "dist/session-notices.js"
    );
    assert_eq!(
        inventory["named_unmapped_with_reason"]["0.81.1_added_modules"][0]["path"],
        "dist/managed-policy.js"
    );
}

fn assert_true_object(value: &Value, expected: &[&str]) {
    assert_exact_object_keys(value, expected);
    for key in expected {
        assert_eq!(value[key], true, "{key}");
    }
}

fn assert_exact_object_keys(value: &Value, expected: &[&str]) {
    let actual = value
        .as_object()
        .expect("object")
        .keys()
        .map(String::as_str)
        .collect::<BTreeSet<_>>();
    let expected = expected.iter().copied().collect::<BTreeSet<_>>();
    assert_eq!(actual, expected);
}

fn assert_exact_string_set(value: &Value, expected: &[&str]) {
    assert_eq!(string_set(value), expected.iter().copied().collect());
}

fn string_set(value: &Value) -> BTreeSet<&str> {
    value
        .as_array()
        .expect("string array")
        .iter()
        .map(|item| item.as_str().expect("string"))
        .collect()
}
