use std::collections::BTreeSet;

#[test]
fn candidate_e_four_route_ledger_reconciles_exactly() {
    const LEDGER: [(&str, &str, &str, bool); 56] = [
        (
            "gemini-cli.acp",
            "model-catalogue",
            "feature.model-catalogue",
            false,
        ),
        (
            "gemini-cli.acp",
            "structured-run",
            "feature.structured-run",
            false,
        ),
        (
            "gemini-cli.acp",
            "interactive-session",
            "feature.interactive-session",
            true,
        ),
        (
            "gemini-cli.acp",
            "route-observation",
            "feature.streaming-events",
            true,
        ),
        (
            "gemini-cli.acp",
            "route-observation",
            "feature.usage-evidence",
            false,
        ),
        (
            "gemini-cli.acp",
            "route-capability",
            "feature.cancellation-or-interruption",
            true,
        ),
        (
            "gemini-cli.acp",
            "route-capability",
            "feature.working-resource",
            true,
        ),
        (
            "gemini-cli.acp",
            "route-capability",
            "feature.bounded-workspace-text-write",
            false,
        ),
        (
            "gemini-cli.acp",
            "route-capability",
            "feature.owned-remote-resource-cleanup",
            false,
        ),
        (
            "gemini-cli.acp",
            "session-lifecycle",
            "feature.persistent-session-posture",
            false,
        ),
        (
            "gemini-cli.acp",
            "route-capability",
            "feature.prepared-facade",
            true,
        ),
        (
            "gemini-cli.acp",
            "route-observation",
            "feature.activity-observation",
            true,
        ),
        (
            "gemini-cli.acp",
            "interactive-session",
            "feature.negotiated-model-options-observation",
            false,
        ),
        (
            "gemini-cli.acp",
            "interactive-session",
            "control.harness-mode",
            true,
        ),
        (
            "gemini-cli.headless",
            "model-catalogue",
            "feature.model-catalogue",
            false,
        ),
        (
            "gemini-cli.headless",
            "structured-run",
            "feature.structured-run",
            true,
        ),
        (
            "gemini-cli.headless",
            "interactive-session",
            "feature.interactive-session",
            false,
        ),
        (
            "gemini-cli.headless",
            "route-observation",
            "feature.streaming-events",
            true,
        ),
        (
            "gemini-cli.headless",
            "route-observation",
            "feature.usage-evidence",
            true,
        ),
        (
            "gemini-cli.headless",
            "route-capability",
            "feature.cancellation-or-interruption",
            true,
        ),
        (
            "gemini-cli.headless",
            "route-capability",
            "feature.working-resource",
            true,
        ),
        (
            "gemini-cli.headless",
            "route-capability",
            "feature.bounded-workspace-text-write",
            false,
        ),
        (
            "gemini-cli.headless",
            "route-capability",
            "feature.owned-remote-resource-cleanup",
            false,
        ),
        (
            "gemini-cli.headless",
            "session-lifecycle",
            "feature.persistent-session-posture",
            false,
        ),
        (
            "gemini-cli.headless",
            "route-capability",
            "feature.prepared-facade",
            true,
        ),
        (
            "gemini-cli.headless",
            "route-observation",
            "feature.activity-observation",
            true,
        ),
        (
            "gemini-cli.headless",
            "structured-run",
            "control.model-selection",
            true,
        ),
        (
            "gemini.live",
            "model-catalogue",
            "feature.model-catalogue",
            false,
        ),
        (
            "gemini.live",
            "realtime-media-session",
            "feature.realtime-media-session",
            true,
        ),
        (
            "gemini.live",
            "route-observation",
            "feature.streaming-events",
            true,
        ),
        (
            "gemini.live",
            "route-observation",
            "feature.usage-evidence",
            true,
        ),
        (
            "gemini.live",
            "route-capability",
            "feature.output-token-limit",
            true,
        ),
        (
            "gemini.live",
            "route-capability",
            "feature.reasoning-selection",
            true,
        ),
        (
            "gemini.live",
            "route-capability",
            "feature.cancellation-or-interruption",
            true,
        ),
        (
            "gemini.live",
            "session-lifecycle",
            "feature.planned-connection-rollover",
            true,
        ),
        (
            "gemini.live",
            "session-lifecycle",
            "feature.persistent-session-posture",
            false,
        ),
        (
            "gemini.live",
            "route-capability",
            "feature.prepared-facade",
            true,
        ),
        (
            "gemini.live",
            "route-observation",
            "feature.activity-observation",
            true,
        ),
        (
            "gemini.live",
            "realtime-media-session",
            "control.reasoning-selection",
            true,
        ),
        (
            "gemini.live",
            "realtime-media-session",
            "control.maximum-output-tokens",
            true,
        ),
        (
            "gemini.live",
            "realtime-media-session",
            "control.realtime-media-config",
            true,
        ),
        (
            "gemini.live",
            "realtime-media-session",
            "control.context-window-compression",
            true,
        ),
        (
            "gemini.live",
            "realtime-media-session",
            "control.planned-connection-rollover",
            true,
        ),
        (
            "grok-build.acp",
            "model-catalogue",
            "feature.model-catalogue",
            false,
        ),
        (
            "grok-build.acp",
            "structured-run",
            "feature.structured-run",
            true,
        ),
        (
            "grok-build.acp",
            "interactive-session",
            "feature.interactive-session",
            true,
        ),
        (
            "grok-build.acp",
            "route-observation",
            "feature.streaming-events",
            true,
        ),
        (
            "grok-build.acp",
            "route-observation",
            "feature.usage-evidence",
            true,
        ),
        (
            "grok-build.acp",
            "route-capability",
            "feature.working-resource",
            true,
        ),
        (
            "grok-build.acp",
            "session-lifecycle",
            "feature.persistent-session-posture",
            false,
        ),
        (
            "grok-build.acp",
            "route-capability",
            "feature.prepared-facade",
            true,
        ),
        (
            "grok-build.acp",
            "route-observation",
            "feature.activity-observation",
            true,
        ),
        (
            "grok-build.acp",
            "interactive-session",
            "feature.negotiated-model-options-observation",
            false,
        ),
        (
            "grok-build.acp",
            "structured-run",
            "control.model-selection",
            true,
        ),
        (
            "grok-build.acp",
            "interactive-session",
            "control.model-selection",
            true,
        ),
        (
            "grok-build.acp",
            "interactive-session",
            "control.session-options",
            true,
        ),
    ];
    let rows = LEDGER
        .iter()
        .map(|(route, shape, semantic, _)| {
            (
                (*route).to_owned(),
                (*shape).to_owned(),
                (*semantic).to_owned(),
            )
        })
        .collect::<BTreeSet<_>>();
    assert_eq!(rows.len(), 56);
    assert_eq!(LEDGER.iter().filter(|row| row.3).count(), 39);
    assert_eq!(LEDGER.iter().filter(|row| !row.3).count(), 17);
    assert_eq!(
        LEDGER
            .iter()
            .filter(|row| row.0 == "gemini-cli.acp")
            .count(),
        14
    );
    assert_eq!(
        LEDGER
            .iter()
            .filter(|row| row.0 == "gemini-cli.headless")
            .count(),
        13
    );
    assert_eq!(
        LEDGER.iter().filter(|row| row.0 == "gemini.live").count(),
        16
    );
    assert_eq!(
        LEDGER
            .iter()
            .filter(|row| row.0 == "grok-build.acp")
            .count(),
        13
    );
}
